export const CREATE_ORDER_PENDING = "CREATE_ORDER_PENDING";
export const CREATE_ORDER_FULLFILLED = "CREATE_ORDER_FULLFILLED";
export const CREATE_ORDER_REJECTED = "CREATE_ORDER_REJECTED";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const ORDER_INFO_PENDING = "ORDER_INFO_PENDING";
export const ORDER_INFO_FULLFILLED = "ORDER_INFO_FULLFILLED";
export const ORDER_INFO_REJECTED = "ORDER_INFO_REJECTED";

export const ORDER_PAY_PENDING = "ORDER_PAY_PENDING";
export const ORDER_PAY_FULLFILLED = "ORDER_PAY_FULLFILLED";
export const ORDER_PAY_REJECTED = "ORDER_PAY_REJECTED";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const FETCH_USER_ORDERS_PENDING = "FETCH_USER_ORDERS_PENDING";
export const FETCH_USER_ORDERS_FULLFILLED = "FETCH_USER_ORDERS_FULLFILLED";
export const FETCH_USER_ORDERS_REJECTED = "FETCH_USER_ORDERS_REJECTED";

export const FETCH_ORDERS_PENDING = "FETCH_ORDERS_PENDING";
export const FETCH_ORDERS_FULLFILLED = "FETCH_ORDERS_FULLFILLED";
export const FETCH_ORDERS_REJECTED = "FETCH_ORDERS_REJECTED";

export const ORDER_DELIVER_PENDING = "ORDER_DELIVER_PENDING";
export const ORDER_DELIVER_FULLFILLED = "ORDER_DELIVER_FULLFILLED";
export const ORDER_DELIVER_REJECTED = "ORDER_DELIVER_REJECTED";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
