export const ORDER_CREATE_PENDING = "ORDER_CREATE_PENDING";
export const ORDER_CREATE_FULLFILLED = "ORDER_CREATE_FULLFILLED";
export const ORDER_CREATE_REJECTED = "ORDER_CREATE_REJECTED";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_INFO_PENDING = "ORDER_INFO_PENDING";
export const ORDER_INFO_FULLFILLED = "ORDER_INFO_FULLFILLED";
export const ORDER_INFO_REJECTED = "ORDER_INFO_REJECTED";

export const ORDER_PAY_PENDING = "ORDER_PAY_PENDING";
export const ORDER_PAY_FULLFILLED = "ORDER_PAY_FULLFILLED";
export const ORDER_PAY_REJECTED = "ORDER_PAY_REJECTED";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const FETCH_USER_ORDERS_PENDING = "FETCH_USER_ORDERS_PENDING";
export const FETCH_USER_ORDERS_FULLFILLED = "FETCH_USER_ORDERS_FULLFILLED";
export const FETCH_USER_ORDERS_REJECTED = "FETCH_USER_ORDERS_REJECTED";