export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_FULLFILLED = "FETCH_PRODUCTS_FULLFILLED";
export const FETCH_PRODUCTS_REJECTED = "FETCH_PRODUCTS_REJECTED";

export const FETCH_PRODUCT_BY_ID_PENDING = "FETCH_PRODUCT_BY_ID_PENDING";
export const FETCH_PRODUCT_BY_ID_FULLFILLED = "FETCH_PRODUCT_BY_ID_FULLFILLED";
export const FETCH_PRODUCT_BY_ID_REJECTED = "FETCH_PRODUCT_BY_ID_REJECTED";

export const DELETE_PRODUCT_PENDING = "DELETE_PRODUCT_PENDING";
export const DELETE_PRODUCT_FULLFILLED = "DELETE_PRODUCT_FULLFILLED";
export const DELETE_PRODUCT_REJECTED = "DELETE_PRODUCT_REJECTED";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

export const CREATE_PRODUCT_PENDING = "CREATE_PRODUCT_PENDING";
export const CREATE_PRODUCT_FULLFILLED = "CREATE_PRODUCT_FULLFILLED";
export const CREATE_PRODUCT_REJECTED = "CREATE_PRODUCT_REJECTED";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const UPDATE_PRODUCT_PENDING = "UPDATE_PRODUCT_PENDING";
export const UPDATE_PRODUCT_FULLFILLED = "UPDATE_PRODUCT_FULLFILLED";
export const UPDATE_PRODUCT_REJECTED = "UPDATE_PRODUCT_REJECTED";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const CREATE_PRODUCT_REVIEW_PENDING = "CREATE_PRODUCT_REVIEW_PENDING";
export const CREATE_PRODUCT_REVIEW_FULLFILLED = "CREATE_PRODUCT_REVIEW_FULLFILLED";
export const CREATE_PRODUCT_REVIEW_REJECTED = "CREATE_PRODUCT_REVIEW_REJECTED";
export const CREATE_PRODUCT_REVIEW_RESET = "CREATE_PRODUCT_REVIEW_RESET";
