export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";
export const GET_PRODUCTS_FULLFILLED = "GET_PRODUCTS_FULLFILLED";
export const GET_PRODUCTS_REJECTED = "GET_PRODUCTS_REJECTED";
export const GET_PRODUCT_BY_ID_PENDING = "GET_PRODUCT_BY_ID_PENDING";
export const GET_PRODUCT_BY_ID_FULLFILLED = "GET_PRODUCT_BY_ID_FULLFILLED";
export const GET_PRODUCT_BY_ID_REJECTED = "GET_PRODUCT_BY_ID_REJECTED";