export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_FULLFILLED = "USER_LOGIN_FULLFILLED";
export const USER_LOGIN_REJECTED = "USER_LOGIN_REJECTED";
export const USER_LOGOUT = "USER_LOGOUT";

export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_FULLFILLED = "FETCH_USER_FULLFILLED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";

export const USER_REGISTER_PENDING = "USER_REGISTER_PENDING";
export const USER_REGISTER_FULLFILLED = "USER_REGISTER_FULLFILLED";
export const USER_REGISTER_REJECTED = "USER_REGISTER_REJECTED";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_UPDATE_PENDING = "USER_UPDATE_PENDING";
export const USER_UPDATE_FULLFILLED = "USER_UPDATE_FULLFILLED";
export const USER_UPDATE_REJECTED = "USER_UPDATE_REJECTED";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
export const FETCH_USERS_FULLFILLED = "FETCH_USERS_FULLFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";

export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_FULLFILLED = "DELETE_USER_FULLFILLED";
export const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const ADMIN_FETCH_USER_PENDING = "ADMIN_FETCH_USER_PENDING";
export const ADMIN_FETCH_USER_FULLFILLED = "ADMIN_FETCH_USER_FULLFILLED";
export const ADMIN_FETCH_USER_REJECTED = "ADMIN_FETCH_USER_REJECTED";

export const ADMIN_UPDATE_USER_PENDING = "ADMIN_UPDATE_USER_PENDING";
export const ADMIN_UPDATE_USER_FULLFILLED = "ADMIN_UPDATE_USER_FULLFILLED";
export const ADMIN_UPDATE_USER_REJECTED = "ADMIN_UPDATE_USER_REJECTED";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";
