export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_FULLFILLED = "USER_LOGIN_FULLFILLED";
export const USER_LOGIN_REJECTED = "USER_LOGIN_REJECTED";
export const USER_LOGOUT = "USER_LOGOUT";

export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_FULLFILLED = "FETCH_USER_FULLFILLED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";

export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";
export const REGISTER_USER_FULLFILLED = "REGISTER_USER_FULLFILLED";
export const REGISTER_USER_REJECTED = "REGISTER_USER_REJECTED";
export const REGISTER_USER_RESET = "REGISTER_USER_RESET";

export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_FULLFILLED = "UPDATE_USER_FULLFILLED";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
export const FETCH_USERS_FULLFILLED = "FETCH_USERS_FULLFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";

export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_FULLFILLED = "DELETE_USER_FULLFILLED";
export const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const ADMIN_FETCH_USER_PENDING = "ADMIN_FETCH_USER_PENDING";
export const ADMIN_FETCH_USER_FULLFILLED = "ADMIN_FETCH_USER_FULLFILLED";
export const ADMIN_FETCH_USER_REJECTED = "ADMIN_FETCH_USER_REJECTED";

export const ADMIN_UPDATE_USER_PENDING = "ADMIN_UPDATE_USER_PENDING";
export const ADMIN_UPDATE_USER_FULLFILLED = "ADMIN_UPDATE_USER_FULLFILLED";
export const ADMIN_UPDATE_USER_REJECTED = "ADMIN_UPDATE_USER_REJECTED";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";
